### ISSUE TITLE
Possible NPE caused by incorrect pointer check

### ISSUE THREAD

**Issue by LostVector** [boostorg/process#118]
My static analyzer is complaining about a possible null pointer exception at https://github.com/boostorg/process/blame/develop/include/boost/process/detail/posix/executor.hpp#L283.

This code was added in commit https://github.com/boostorg/process/commit/1b476b0430d6cb30a4b1027074f15d658153de2e.

I believe this NPE is caused by the if statement at https://github.com/boostorg/process/blame/develop/include/boost/process/detail/posix/executor.hpp#L280.  It seems like it should be checking against *e, not e.

**Comment by klemens-morgenstern** [comment]
I think this has been addresses by 1b476b0430d6cb30a4b1027074f15d658153de2e, still testing though.

**Comment by LostVector** [comment]
Don't think this fixes it, the code is just moved but not changed.

Again, the line in question should be checking against *e, not e.  e itself will never be a nullptr because it's a pointer into the environment string.
