### ISSUE TITLE
Leak child process if execv faild

### ISSUE THREAD

**Issue by dvetutnev** [boostorg/process#151]
Test: https://github.com/odant/conan-boost/blob/develop/test_package/test_boost_process_leak_child.cpp
Patch: https://github.com/odant/conan-boost/blob/develop/fix_leak_child_process.patch

**Comment by pogaram** [comment]
It seems there is also a pipe leak in this case.

**Comment by arconamagi** [comment]
Are there any news on this issue? Was it fixed?

**Comment by martinus** [comment]
@klemens-morgenstern is this a duplicate of #265, can this now be closed?

**Comment by klemens-morgenstern** [comment]
I think so.
