### ISSUE TITLE
async_pipe constructor throws exception for already existing pipe

### ISSUE THREAD

**Issue by ankitbhadoria21** [boostorg/process#156]
if the pipe name already exists the constructor for async_pipe throws exception, which makes it impossible to use it for inter-process communication between two separate processes.

**Comment by ankitbhadoria21** [comment]
`
async_pipe::async_pipe(boost::asio::io_context & ios_source,

                       boost::asio::io_context & ios_sink,

                       const std::string & name) : _source(ios_source), _sink(ios_sink)

{

    auto fifo = mkfifo(name.c_str(), 0666 );



    if (fifo != 0)

        boost::process::detail::throw_last_error("mkfifo() failed");`

**Comment by klemens-morgenstern** [comment]
Well aware, the pipes are not meant to be used that way. Using them for IPC by pipe name will be a lot more work, and should probably be a different library.
