### ISSUE TITLE
Add support for replacing Boost.Fileystem with C++17 <filesystem> when available

### ISSUE THREAD

**Issue by cmazakas** [boostorg/process#207]
Boost.Process is a wonderful library but existed for longer than C++17 compilers have and as such, its API is polluted with `boost::filesystem::path`. This causes an awkward disconnect when being used in C++17 projects.

This issue aims to start a discussion addressing this issue and the best path forward for giving C++17 users a way of using `std::filesytem::path`.

**Comment by MJBGO** [comment]
+1 for with that one ! It seems that Boost DLL is using the flag BOOST_DLL_USE_STD_FS for backword compatibility with C++11.

**Comment by laanwj** [comment]
+1 to this, we ran into a similar issue

**Comment by ingo-loehken** [comment]
+1 for this. should be removed or be configurable like for boost.dll.
