### ISSUE TITLE
Reusing the same boost::process::async_pipe for both stderr and stdout 

### ISSUE THREAD

**Issue by linkret** [boostorg/process#225]
I came across differing behavior under Windows and Linux. This code snippet works and runs fine under Windows, but throws an exception when trying to run on Linux (Debian10). I'm not sure if it's a bug or not, so I'm posting it here just in case. Perhaps this is not an issue at all. I was using boost 1.77, built with support for C++20, llvm. 

```
_proc_ptr = std::make_unique<bp::child>(
	bp::exe = cmd,
	bp::args = args,
	bp::std_in < stdin,
	bp::std_out > _out,
	bp::std_err > _out,
	_ioc,
	bp::on_exit = _exit_fun
);
```

_out is a boost::process::async_pipe, and I use async_read_some() to initiate the reading of the process's std_out and std_err streams. 

Under Linux the process fails to launch, and throws a std::exception with the .what() message "Bad file descriptor". I tried it with several different executibles I tried to launch, including my own dummy one (which just echoes messages back with cerr and cout), SSH, and a few more.

The workaround was for me to add another async_pipe (let's say _err), and say `bp::std_out > _out, bp::std_err > _err`, but my question is: why did the original code work under Windows? And should redirecting two streams into the same pipe work on Linux as well? Or is it expected behavior for it to not work? I wasn't able to find this information in the provided examples and documentation. 

Thank you.

**Comment by klemens-morgenstern** [comment]
That's an interesting problem. Both close the used handle during the process launch, but apparently that doesn't work well on unix. Can you copy the the _out first?

```cpp
auto err = _out; //duplicate handles
_proc_ptr = std::make_unique<bp::child>(
	bp::exe = cmd,
	bp::args = args,
	bp::std_in < stdin,
	bp::std_out > _out,
	bp::std_err > err,
	_ioc,
	bp::on_exit = _exit_fun
);

```

**Comment by garethsb** [comment]
Doesn't `(bp::std_out & bp::std_err) > _out` do what you wanted?

**Comment by linkret** [comment]
> Doesn't `(bp::std_out & bp::std_err) > _out` do what you wanted?

Sounds like it might, I'll try it tomorrow, thank you.

**Comment by jmccabe** [comment]
Did it?

**Comment by linkret** [comment]
It did, yes.

**Comment by jmccabe** [comment]
Thank you.
