### ISSUE TITLE
passing a process id to get its environment block, executable image path, working directory, command line, window id's, etc. and enumerate all running processes

### ISSUE THREAD

**Issue by time-killer-games** [boostorg/process#244]
I wrote some things for my own process library I'd like to contribute to the boost process library.

Source code here:
https://github.com/time-killer-games/xproc/blob/main/apiprocess/process.cpp

As explained in the title, this is capable of getting environ, cmdline, cwd, exe, and wid of an arbitrary pid. The wid, or Window ID, on Windows is an std::to_string((uintptr_t)(void *)HWND), on Mac it is a std::to_string((uintptr_t)CGWindowID) though not sure if iOS has CGWindowID or something else) and on Linux currently only X11 Xlib windows are supported, but Wayland and the Android "equivalent" will be added in the future, i.e. X11 Xlib Window ID would be std::to_string((uintptr_t)Window). A CGWindowID is a typedef of an unsigned int. An Xlib Window is a typedef of unsigned long. And of course a Windows HWND is a typedef of a void *. The Window ID doesn't need to be a string; I only did that for easy concatenation in shell scripting and to unify each platform to use the same datatype underneath to represent a window. Although I admit using a string is slow and not all that practical otherwise.

I also support getting a list of all processes running in the current user session.

I support currently Windows, macOS, Linux, FreebSD, DragonFly BSD, and OpenBSD. I plan to support NetBSD and Illumos as well. As far as I know, though I haven't tested, iOS and Android should also be supported, iOS would need to run in Developer mode to have access to certain features that aren't allowed on the AppStore. Android would require libprocps from linux world to be compiled specifically for Android, although I'm not sure if Android supports all the same procfs stuff that Linux does.

I was wondering if these ideas would be considered at all for a future release of boost process if I were to make a pull request and listen to all of your code review critiques. Also I think it would be good to having Window ID stuff only available to the user when enabled via a macro defined at compile time, as there are a lot of platforms that don't even have a windowing system that I'd like to support and would prefer to not rely on for example Xlib or Wayland by default because that isn't 100% needed.

The only platforms that have dependencies are Linux and Android (libprocps)

Let me know what you think.
Samuel

**Comment by time-killer-games** [comment]
Would you by any chance be ok with making a new repository with a basic skeleton for the structure of how you want the new library to implemented? Then it would just be a matter of plugging in and adapting my existing code to the relevant places in a pull request?

It was called "xproc" to imply "cross-platform process library" but now I can see it could also imply "cross-process" or inter-process exchange of process information, which would be a very specific and niche type of IPC so it would probably need a name that reflects what it does more specifically. I'll let you decide how that should be done if you are really thinking about doing this. :) Maybe something that could differentiate it from the existing boost ipc module.

**Comment by time-killer-games** [comment]
Additonal information about this issue I posted here may also be found where I suggested adding these features to SDL2.

https://github.com/libsdl-org/SDL/issues/5570

More specifically, this bit I failed to mention on my original boost issue:

> Windows currently can only read some process information based on processes that are the same architecture as the calling process, and i do have a means to read between 64-bit <-> 32-bit x86 but it's rather convoluted and crashes when built with MSVC instead if MinGW, so I already know it won't be approved of in my PR. This would include the following:
> 
>     cmdline from pid
>     environ from pid
>     cwd from pid
> 
> note there is a more ideal way to read a cmdline on windows using COM which will work across 32-bit <> 64-bit x86 and will also not rely on the undocumented structure i am currently using for this on windows, but the COM implementation will not work on Windows executables that are run through WINE on non-Windows platforms so it is probably better to use my current approach depending on your preference. Either way it is a bit limiting for reasons given, regardless of approach.
> 
> Only one other feature is currently planned:
> 
>     get all hardlinks associated with file descriptor opened by process id
> 
> This will rely on scanning the whole filesystem on OpenBSD while checking a match of pid, fd, dev, inode, and other things. There will be an error code when the file size and other things don't match up to indicate the file was either modified or there was a potential race condition. There will also be a timeout interval and an error code the user can check for and if they wish to continue the search they may do so in a while loop and pick up on traversing the filesystem where they left off. This is to avoid long hanging. On Windows i will likely need another private API or perhaps dll injection. The other platforms that I've messed with have much more clean solutions and are the OS developers' "best effort". The OpenBSD solution might have to be considered for other platforms as well depending on the API's available.

Alternatively I could look into dll injection to get the 32-bit <-> 64-bit Windows communication more reliably, but that will take a while at this stage as DLL injection I've looked into in the past and it was fairly difficult to wrap my brain around with so little information on it floating around the web.

**Comment by time-killer-games** [comment]
and last little note I wanted to make of here so I can remember to mention it in the documentation -

All platforms retrieve the cmdline and environ values based on their current state they were in when the calling process tries to retrieve them -- except macOS and iOS --  they get the cmdline and environ based on the initial state of their values when the process is first launched, so if their values ever get modified you will not be able to get their values in a way that works the same on non-Apple/Darwin/XNU kernel platforms.

Let's say i ran from the terminal:

env NAME=VALUE ./executable --arg1 --arg2 --arg3

then in the process's C++ source execution it eventually calls

setenv("NAME", "NEWVALUE") // or the cmdline vector was modified too for example: ./application --param1 --param2 --param3

on mac/apple, it would return `NAME=VALE` and `./executable --arg1 --arg2 --arg3` no matter what because it only returns the initial state of those values.

On other platforms, if the code execution reach a point where setenv ws called and the cmdline vector were both modified like above, it would return the new values instead, thus it would return differently than the expected behavior on apple platforms:

`NAME=NEWVAUE` and `./application --param1 --param2 --param3` for example.

**Comment by time-killer-games** [comment]
I added full support for NetBSD since the time I posted this. :)

**Comment by klemens-morgenstern** [comment]
I can spin up some basic repo, so we do it outside of process. That wouldn't preclude it from being moved into process later.

You got a projectg name idea for the meantime?

I wrote you an email btw..

**Comment by time-killer-games** [comment]
@klemens-morgenstern hey! Sounds great.

You were automatically put in my spam box so I didn't see it immediately. I marked you as "Not spam" and saved your contact. :)

As for the name, I'm not sure. It would need to have some means to be differentiated from the other process libs. If you can't think of anything you find better, we can stick with xproc.

**Comment by klemens-morgenstern** [comment]
Heya mate, I create a repo here (just put it in the boost namespace, being optimistic here) https://github.com/klemens-morgenstern/xproc

You got access rights, so let's move the conversation over tehre.
