### ISSUE TITLE
noexcept

### ISSUE THREAD

**Issue by garethsb** [boostorg/process#25]
I'm just wondering whether it's intentional that Boost.Process doesn't support Visual Studio 2013 due to use of `noexcept` rather than `BOOST_NOEXCEPT`? (Someone raised this [in trac](https://svn.boost.org/trac10/ticket/13214) for VS2012, but it also applies to VS2013.)

**Comment by klemens-morgenstern** [comment]
Sort of - boost.process requires C++11 for `noexcept` and req-qualifiers. Now you can work around the first for VS2012, but the second will still bite you. So I don't see the point of using `BOOST_NOEXCEPT`.

**Comment by garethsb-sony** [comment]
Visual Studio 2013 RTM doesn't support ref-qualifiers, although the CTP Nov 2013 update does I think. But if the answer is Boost.Process supports VS 2015 minimum, that's a clear statement, thanks.

(I was initially only looking to use cross platform boost::this_process::get_id() anyway.)

**Comment by klemens-morgenstern** [comment]
Well I said I don't see the point not that there isn't a case. If you have a workaround that doesn't impact the current design (as in removing ref-qualifiers) but gives you an application (like this_process) feel free to submit a PR. I just won't consider that supported. Btw. I don't think in terms of compiler support, but language and platform support, i.e. it's C++11 and posix or windows, that I aim to support.

**Comment by garethsb-sony** [comment]
OK, thanks.

I prefer to think in terms of language revisions too, but unfortunately it's compilers that I have to work with. :-)
