### ISSUE TITLE
Support BOOST_NO_ANSI_APIS

### ISSUE THREAD

**Issue by hia3** [boostorg/process#26]
#define BOOST_NO_ANSI_APIS 1
    #include <boost/process.hpp>
    int main() {}

Fails to compile with: 

    boost/process/detail/windows/locale.hpp(44): error C3861: 'AreFileApisANSI': identifier not found

**Comment by klemens-morgenstern** [comment]
Thanks for the report. Can you share what compiler and what windows version you use?

**Comment by klemens-morgenstern** [comment]
Out of curiosity, why do you use `BOOST_NO_ANSI_APIS` ?

**Comment by hia3** [comment]
> Out of curiosity, why do you use BOOST_NO_ANSI_APIS ?

ANSI is an endless source of bugs, more on this here: http://utf8everywhere.org/

You might know already, that Boost.Nowide is accepted into Boost (not included yet), here is what it recommends: http://cppcms.com/files/nowide/html/index.html#using_custom

Also I think I had some compilation problem trying to compile some version of Boost with some vesion of clang on Windows, but now I can't tell what the probles was.

**Comment by klemens-morgenstern** [comment]
Ok, well then let's turn that into a supporting the `BOOST_NO_ANSI_APIS` issue then, so we're clear on the goal here.

**Comment by hia3** [comment]
Thanks for the fix.
Although, the example compiles now, it is still ill-formed.

Compiling with `-fno-delayed-template-parsing` (clang) produces:

[boost/process/detail/windows/basic_pipe.hpp:147:13](https://github.com/boostorg/process/blob/develop/include/boost/process/detail/windows/basic_pipe.hpp#L147): error: cannot initialize a parameter of type 'boost::winapi::LPCWSTR_' (aka 'const wchar_t *') with an rvalue of type 'const char *'
            name.c_str(),
            ^~~~~~~~~~~~
boost/winapi/pipes.hpp:265:14: note: passing argument to parameter 'lpName' here
    LPCWSTR_ lpName,
             ^

It compiles without the flag because [no diagnostic required](https://github.com/cplusplus/draft/blob/a88d02d8d77e730bbf2730b6988a8b63319496c3/source/templates.tex#L4185).
