### ISSUE TITLE
boost::process::detail::posix::execvpe Is Async Signal Safely ?

### ISSUE THREAD

**Issue by fcharlie** [boostorg/process#28]
Deadlock may occur if you execute boost.process code in a multithreaded program
 
https://github.com/boostorg/process/blob/develop/include/boost/process/detail/posix/executor.hpp#L33-L64

std::string and std::vector require allocate memory. When other thread lock this, child process mybe deadlock.

**Comment by klemens-morgenstern** [comment]
I am not sure I follow you here. Those are different processes with differend mempages at this point, why would that lead to a deadlock?

**Comment by klemens-morgenstern** [comment]
I just remembered, we had another discussion about this issue here: https://github.com/klemens-morgenstern/boost-process/issues/65

I still don't know how to solve that though,

**Comment by fcharlie** [comment]
Your can use execve and resolve filename before fork

**Comment by klemens-morgenstern** [comment]
Closing it in favor of the other issue. Will look into it.
