### ISSUE TITLE
Support BOOST_ASIO_NO_DEPRECATED

### ISSUE THREAD

**Issue by hia3** [boostorg/process#29]
#define BOOST_ASIO_NO_DEPRECATED 1
    #include <boost/process.hpp>
    int main() {}

Error:

    boost/process/detail/windows/async_pipe.hpp:102:39: error: no member named 'get_io_context' in 'boost::asio::windows::stream_handle'
            _sink = handle_type(_sink.get_io_context());

**Comment by klemens-morgenstern** [comment]
It might be a good idea to support that, but - I'm sorry to say -  I won't get around to implement that anytime soon. I'd accept PRs though

**Comment by krojew** [comment]
This would be a good addition, since boost::process now fails to build whenever this define is used.

**Comment by klemens-morgenstern** [comment]
Fixed, will publish soon.
