### ISSUE TITLE
boost::process::detail::posix::eval_exit_status may return 0 if child received SIGABRT

### ISSUE THREAD

**Issue by hrayrbabajanyan** [boostorg/process#31]
In case if child received SIGABRT WIFEXITED() may be false and WEXITSTATUS() will result in 0.

proposed change:
```
// from
inline int eval_exit_status(int code)
{
    return WEXITSTATUS(code);
}
// to
inline int eval_exit_status(int code)
{
        if (WIFEXITED(code))
        {
                return WEXITSTATUS(code);
        }
        else if (WIFSIGNALED(code))
        {
                return WTERMSIG(code);
        }
        else if (WIFSTOPPED(code))
        {
                return WSTOPSIG(code);
        }
        else
        {
                return code;
        }
}
```

**Comment by klemens-morgenstern** [comment]
Thanks for reporting, that would make sense. I'll have to check if that would make it incompatible with something on windows first though.

**Comment by hrayrbabajanyan** [comment]
Hi Klemens,

I copied the code from my own process library that I am replacing with
boost.process. The suggested code make exit codes compatible with windows
and *nix shell.
Please review it. And should you have questions please don't hesitate to
ask.

Regards,
Hrayr

--
Hrayr BABAJANYAN
e-mail: hrayr.babajanyan@gmail.com
   url: www.babajanyan.com
mobile: +374 93 747297
office: +374 60 448471
   fax: +374 10 542927

**Comment by klemens-morgenstern** [comment]
If you create a PR (against www.github.com/klemens-morgenstern/boost-process) and the CI runs through I'll merge it, otherwise I'll do that myself on the weekend. I have a bunch of open issues in the library that I should address soon.

**Comment by klemens-morgenstern** [comment]
Since it's merged, I'm closing the PR. Let me know if you find anything else and thanks!

**Comment by hrayrbabajanyan** [comment]
Thanks!

--
Hrayr BABAJANYAN
e-mail: hrayr.babajanyan@gmail.com
   url: www.babajanyan.com
mobile: +374 93 747297
office: +374 60 448471
   fax: +374 10 542927
