### ISSUE TITLE
Process V2: Example fails to build when using BOOST_ASIO_SEPARATE_COMPILATION

### ISSUE THREAD

**Issue by reddwarf69** [boostorg/process#318]
As can be seen in [https://godbolt.org/z/q3r4hjGsd](https://godbolt.org/), https://github.com/boostorg/process/blob/develop/example/v2/intro.cpp fails to build when using BOOST_ASIO_SEPARATE_COMPILATION.

(in general, not sure why asio::detail is used to start with)

**Comment by klemens-morgenstern** [comment]
FYI: This is a copy-pasta mistake. process.v2 was originally a PR to go into asio itself.
