### ISSUE TITLE
[v2] Using async_execute with bind_cancellation_slot

### ISSUE THREAD

**Issue by Chardrazle** [boostorg/process#338]
I've been cutting over some _process_ v1 code to v2, and (due to the asynchronous nature of the use-case) went via the `async_execute` route (and _asio_).

It's all good except for the `cancellation_signal`, insofar as `total` and `partial` have no effect on the child process.  
The code has been written in a similar manner to the example, with a (timer) fallback through `total`/`partial` and then `terminate`, with the latter successfully pulling the plug.  
However, this isn't ideal as I really need the _SIGINT_ detection for clean up (in the child process).

The child process in this case is a _bash_ script, with _trap_ handlers.  Those handlers are never invoked.

I do see in the code for `async_execute`:
>  * It is to note that `async_execute` will us the lowest selected cancellation
>  * type. A subprocess might ignore anything not terminal.

So perhaps this is expected behaviour.  If that is the case, then what should be the approach?
The original v1 code went directly to `kill(..., SIGINT);`

**Comment by klemens-morgenstern** [comment]
I am happy to hear v2 is working for you.

`total` should lead to a `SIGINT` and `partial` to a `SIGTERM`, actually: https://github.com/boostorg/process/blob/develop/include/boost/process/v2/execute.hpp#L56C1-L62C38

Is that what you'd expect?

Are you using something in between the cancellation and the async_execute, like an `awaitable` or a yield_context`?
If so, these will by default filter out anything not `terminal`, which might explain your issue. If not, then it's a bug in my code.

**Comment by Chardrazle** [comment]
That is what I was expecting, but the child process does not appear to be receiving the `total` nor `partial`; the `terminal` is the one that does get through, and then it pulls the plug.

One thing of note: I am running the _asio_ context in a thread - maybe that is being treated differently?  
The _bash_ script never receives the `SIGINT`.  If I drop to a shell and run "kill -s INT \<proc\>" then it does.  

I've stripped back the code to a test-case; please take a look to see if I've made an incorrect assumption.  
(renamed as .txt because cpp was not allowed !)  
[bpv2_sig.cpp.txt](https://github.com/boostorg/process/files/12565991/bpv2_sig.cpp.txt)

**Comment by klemens-morgenstern** [comment]
Found it. The `async_execute` uses a composed op, which internally has a cancellation_state, that filters out anything not terminal. I'll have a patch in a few minutes.

**Comment by klemens-morgenstern** [comment]
@Chardrazle does [a3259dc](https://github.com/boostorg/process/commit/a3259dc5f774c3c87a4230d2e3cf0eeed1a686ab) fix it for you?

**Comment by Chardrazle** [comment]
I tried against the sample program provided here and do not see any different behaviour.

**Comment by Chardrazle** [comment]
@klemens-morgenstern sorry, maybe my comment was misinterpreted.
When I said I didn't see any different behaviour, I meant that the patch did not make any difference; i.e. it does _not_ fix the issue as exhibited in the test case that is provided here.

**Comment by klemens-morgenstern** [comment]
Sure, but I fixed a bug and have a test showing it sends SIGINT & SIGTERM. 

I think we'd need to dig further down into your code then.
