### ISSUE TITLE
How send Ctrl+C to child process?

### ISSUE THREAD

**Issue by KindDragon** [boostorg/process#4]
I want to terminate my child `git` process

**Comment by klemens-morgenstern** [comment]
Terminate can be done with `child::terminate`, but Strg+C is not supported, because there is no portable way to do so.

**Comment by KindDragon** [comment]
What you mean by "no portable way"? Your library have a lot of custom code for Windows and Posix

**Comment by KindDragon** [comment]
> Terminate can be done with child::terminate

It will terminate only one process, not a whole child process tree

**Comment by klemens-morgenstern** [comment]
Strg+C is an interrupt, and there is no unified way to do that on windows. Thus it wouldn't be portable, because it would not work the same on both platforms. 
If you want to terminate the whole process tree you can use `group`.

**Comment by KindDragon** [comment]
> Strg+C is an interrupt, and there is no unified way to do that on windows.

On Windows you have `GenerateConsoleCtrlEvent`

**Comment by klemens-morgenstern** [comment]
I know, but that does only works for console processes, not for those with a window. That's what I mean by not portable.

**Comment by klemens-morgenstern** [comment]
You can of course still use that, when you obtain child handle through `child::native_handle`.

**Comment by KindDragon** [comment]
Ok, maybe sometime in the long distant future you will be supporting Ctrl+C 😄

**Comment by klemens-morgenstern** [comment]
Probably never, I only put in features that work similar on both platforms. An `interrupt` does not qualify, but if you have a design idea or maybe even a implementation, I'll definitely take a look.
