### ISSUE TITLE
Feature request, support compilation with std's filesystem library

### ISSUE THREAD

**Issue by correaa** [boostorg/process#43]
Boost.Process depends on Boost.Filesystem, mainly because of boost::filesystem::path.
Now that Filesystem is in the standard (almost?) I think it would be nice to have the option for Boost.Process to compile against std's filesystem (`#include<experimental/filesystem>`) instead of `#include<boost/filesystem.hpp>`.

**Comment by egorpugin** [comment]
See https://github.com/klemens-morgenstern/boost-process/issues/164

**Comment by klemens-morgenstern** [comment]
Closed bc duplicate.
