### ISSUE TITLE
Sparring_partner.exe crashed when execute 2 tests(bind_stdin_stdout and exit_code) on windows

### ISSUE THREAD

**Issue by PhoebeHui** [boostorg/process#53]
We tried to build and run process test with visual studio latest release on Windows. Sparring_partner.exe crashed when execute 2 tests(bind_stdin_stdout and exit_code), could you please help take a look at this? Thank you!
Reproduce steps:
1.	git clone -c core.autocrlf=true --recursive https://github.com/boostorg/boost.git D:\Boost\src
2.	open a VS 2017 x86 command prompt and browse to D:\Boost\src
3.	.\bootstrap
4.	.\b2 headers variant=release --build-dir=..\out\x86rel address-model=32
5.	.\b2 variant=release --build-dir=..\out\x86rel address-model=32
6.	.\b2 -j4 variant=release –d+2 --build-dir=..\out\x86rel libs\process\test

Sparring_partner.exe crashed when execute steps  "..\out\x86rel\boost\bin.v2\libs\process\test\exit_code.test\msvc-14.1\release\threading-multi\exit_code.exe"  "..\out\x86rel\boost\bin.v2\libs\process\test\msvc-14.1\release\threading-multi\sparring_partner.exe" > "..\out\x86rel\boost\bin.v2\libs\process\test\exit_code.test\msvc-14.1\release\threading-multi\exit_code.output" 2>&1” 

It also crashed when run ‘bind_stdin_stdout’ test.

**Comment by PhoebeHui** [comment]
It doesn't crash, the ERRORLEVEL is 0.

**Comment by klemens-morgenstern** [comment]
Ok, I'll see if can reproduce it.

**Comment by klemens-morgenstern** [comment]
This happens because `sparring_partner` calls `std::abort` - this is not a bug, just press ignore.
