### ISSUE TITLE
Use PATHEXT for expanding executable extensions

### ISSUE THREAD

**Issue by pravic** [boostorg/process#6]
Currently it uses hardcoded limited [set of them](https://github.com/boostorg/process/blob/develop/include/boost/process/detail/windows/search_path.hpp#L35): `"", ".exe", ".com", ".bat"`, but it is not correct.

**Comment by klemens-morgenstern** [comment]
Oh ok, what's the error?

**Comment by klemens-morgenstern** [comment]
closed in favor of the other repository.
