### ISSUE TITLE
Race in process::child and a bad fix

### ISSUE THREAD

**Issue by pfaffe** [boostorg/process#60]
In 1.65, there was a race when using `boost::process::child::wait_for`. Compiling the attached [example](https://github.com/boostorg/process/files/2680177/flaky_children.txt) with C++17 and gcc 7.3 on linux (although other version and clang are affected too) sometimes produces the expected output
```
$ ./a.out foo
Timeout
Finished
```
And sometimes immediately without waiting
```
$ ./a.out foo
Exited with code 252
Finished
```
which I assume is caused by a race somewhere in the fork and pipe setup part.

Interestingly, the bug is gone in 1.69, but I didn't find a ticket for it so I'm still reporting. Mostly because the fix got it wrong, too. Although there is no more race, `wait_for` now sleeps for the given time. Independent of whether the child exits or not. To reproduce, change the `Sleep` timespan to like 3s in the testcase.

**Comment by klemens-morgenstern** [comment]
Thanks for reporting, those functions really are trouble. Can you test against the current masterbrach, I just merged another fiy yesterday and my tests pass.

**Comment by pfaffe** [comment]
With master the issue doesn't reproduce anymore for my testcase and production use case!

Cheers!

**Comment by klemens-morgenstern** [comment]
Awesome, that stuff was a nightmare I tell you.
