### ISSUE TITLE
Poor execvpe support detection

### ISSUE THREAD

**Issue by RedDwarf69** [boostorg/process#63]
Because of https://github.com/boostorg/process/blob/develop/include/boost/process/detail/posix/executor.hpp#L35 boost::process fails to build with uClibc.

While at some point it was added (https://git.uclibc.org/uClibc/commit/?id=0eb30761a26c46aaf555464114851202ae9c27bd), that was after the latest release (0.9.33.2).

**Comment by klemens-morgenstern** [comment]
Thanks for the report - I am not really sure now. Does boost.process wrongfully assumes `execvpe` exists or does it not use if it exists? And how should the detection look?

**Comment by RedDwarf69** [comment]
It supposes that if `__GLIBC__` is defined then the system already provides execvpe(). It's probably certainly true that any glibc version still in use does provide execvpe(). But the check is not precise enough:

- There may be other C libraries other than glibc providing execvpe(), but not defining `__GLIBC__`. IIRC musl refuses to define `__GLIBC__`, and it may actually be defining execvpe(). If I am right, Boost.Process is unnecessarily building its own version of execvpe() when using musl (e.g. current OpenWRT versions).

- There are libraries other than glibc that do define `__GLIBC__`, but may not provide execvpe(). They do this precisely because apps often do like this, and instead of detecting the presence of the feature they just check for the presence of glibc. One specific example of this is any stable release of uClibc. The latest versions of OpenWRT still using uClibc did patch it to include the support, but unpatched versions of uClibc are still in use in lots of embedded devices (for no good reason, but it's a fact I can't change).

Sorry, I don't really know the Boost build system, so I can't provide a patch to check specifically for execvpe().

**Comment by RedDwarf69** [comment]
FWIW Boost.Thread needs to check if there is `lockfree boost::atomic_flag` and it checks for the specific feature in https://github.com/boostorg/thread/tree/develop/build.

There is a `has_atomic_flag_lockfree_test.cpp` file to do the check itself and in Jamfile.v2 there are a few references to it.

I still don't know anything about the Boost build system and, honestly, I don't want to know. But I guess Boost.Process needs something similar.

**Comment by klemens-morgenstern** [comment]
It's not build system issue, process is head only. I just need to have the proper ' #ifdef' to check that. Will see if I can find a solution there.

**Comment by RedDwarf69** [comment]
Again, no idea how things are done in Boost. But I expect any attempt to check for the feature using only headers to fail in some corner case.

Even if doing a header only library, in other projects I would expect the build system to detect if the feature is supported by trying to actually compile/run with it. Then the build system would maybe create a `config.h` header with something like
```
#ifndef BOOST_PROCESS_HAS_EXECVPE
#define BOOST_PROCESS_HAS_EXECVPE 1
#endif
```
(the `1` could be a `0` if the build system finds that the feature is not supported)
to be installed with the rest of the header only library. Other parts of the header only library would `#include "config.h"` to know what the build system has found.

Looking at other header only Boost libraries... Asio seems to do its best to do the detection using only the headers. But I guess knowing that the detection will be imperfect, it puts everything inside a `#if !defined(BOOST_ASIO_HAS_GETADDRINFO)` so the user can override the detection.

**Comment by klemens-morgenstern** [comment]
I also have a header-only detection going, no `boost.config` required. I would also like to keep it that way. Maybe `__GLIBC__` + `not uCLibC` or something.

**Comment by klemens-morgenstern** [comment]
FWIW: I removed usage of execvpe and replaced it with my own solution. Will solve that issue and be in master soon.
