### ISSUE TITLE
Crossplatform process isolation features, process resource monitoring

### ISSUE THREAD

**Issue by msporyshev** [boostorg/process#66]
Hello! Is there any chance that process isolation features or process resource monitoring features will appear in boost.process? Would it be useful for this library to have such things, or is it possible to contribute for them? Some existing solutions are [nsjail](https://github.com/google/nsjail) or [isolate](https://github.com/ioi/isolate), or may be  some others, like docker. 

I'm developing automated testing system for computer science students competitions which requires constrainted sandbox launch of student programs.  All mentioned solutions are either not clossplatform (nsjail) or don't have everything that is needed (docker).

**Comment by klemens-morgenstern** [comment]
I don't think I will find the time to do it. If you have an idea how to integrate that as extensions I would gladly help your efforts. Send me an email if you want to discuss this further.

**Comment by klemens-morgenstern** [comment]
Will close it for now, feel free to reopen if you have an idea how to implement that.
