### ISSUE TITLE
boost v 1.69 - Leaking file descriptors from boost::process::system and boost::process::child

### ISSUE THREAD

**Issue by jussihi** [boostorg/process#98]
I already opened a stackoverflow question, but it seems like this is a bug.

Let's say we have this simple code to flush iptables config every 3 seconds (just an example):

```
#include <boost/process.hpp>
#include <thread>


int main(void)
{
  while(true)
  {
    std::this_thread::sleep_for(std::chrono::seconds(3));
    boost::process::system(boost::process::search_path("iptables"), "-F");
  }
  return 0;
}
```

If we observe the count of open file descriptors by listing `/proc/PID/fd |wc -l`, we can see that the count increases by one every 3 seconds. Eventually, when it reaches 1024, the program will abort, because the system call will throw an exception with what() stating that there are `too many open files!`

Sorry if this is an already known issue.

**Comment by a-andre** [comment]
Seems to be a duplicate of #62

**Comment by jussihi** [comment]
@a-andre , thanks, I will close this one.
